### ISSUE TITLE
Integrate user's permissions and credentilas in Spring Security context

### ISSUE THREAD

**Issue by MarinTrpenovski** [MarinTrpenovski/Spring-Rest#103]
Need to implement Authorization in project.

After the user is successfully authenticated (have valid JWT token) needs to load user permissions from the database (use service that is already created) in order to load user permissions. 
Code implementation should be added in Auth Filter.
Permissions after are loaded from Database  need to be added in Spring Security Context. Also user email and JWT token can be added in spring security context. Its good to have this information in spring security context because any time during request execution you will be available to retrieve information for the user (jwt token, permissions, user email).

Use this link as reference. https://www.baeldung.com/role-and-privilege-for-spring-security-registration

Understand how spring security works, step 4 describe how to load user permissions in spring security context. 

Also this code snippet can help you 

![Image](https://user-images.githubusercontent.com/27773018/264271452-4698cb2e-c2fc-4a11-9633-89aa36a07afa.png)

**Comment by AngelaM123** [comment]
Saw the suggested link and the snipped code , added the required code in the filter  and added user credentials to the security context

**Comment by MarinTrpenovski** [comment]
@AngelaM123 Give explanation about Security Context, how it works and why we need it in web application. What you understand from the link the description.

Also fix following note:
![image](https://github.com/WORK-MENTOR/Spring-Rest/assets/27773018/e7e51803-63a2-47fd-8547-7090ea9aeab3)
This code doesn't do anything important about security, just print permissions and roles in console. Code looks same as one in Test class that have been created. 

![image](https://github.com/WORK-MENTOR/Spring-Rest/assets/27773018/c637ba76-4f3f-4556-a665-560acfb4448d)

I can not see that you have integrated GrantAuthority property in Security context. Also permissions are not added in security context. You just keep jwtToken and userEmail from user which is ok but permissions are not loaded. 
Read carefully link or find other one if this is not understandable , also read description of the issue.

**Comment by AngelaM123** [comment]
For better understanding i was using the official spring security site https://docs.spring.io/spring-security/reference/servlet/authentication/architecture.html#servlet-authentication-authentication
The SecurityContextHolder is where Spring Security stores the details of who is [authenticated](https://docs.spring.io/spring-security/reference/features/authentication/index.html#authentication). Spring Security does not care how the SecurityContextHolder is populated. If it contains a value, it is used as the currently authenticated user. 
We start by creating an empty SecurityContext. Spring Security does not care what type of Authentication implementation is set on the SecurityContext.
We set the SecurityContext on the SecurityContextHolder with method UsernamePasswordAuthenticationToken(userDetails, password, authorities).
Instead of user details i am using userDTO because it contains user email , name , permissions and roles
Also applied the notes that were requested

**Comment by MarinTrpenovski** [comment]
@AngelaM123 The Code looks good now.

The explanation is also correct. I think you get the point about Spring Security and how it works in spring and the web projects.

Closing issue now.
