### ISSUE TITLE
Create search endpoints

### ISSUE THREAD

**Issue by MarinTrpenovski** [MarinTrpenovski/Spring-Rest#14]
For each of the entities create search REST endpoints. 
Each of the REST endpoint should accept different query parameters so you should be able to create search criteria using them.
Based on the properties that each of the entities have in DB apply different query parameters in the URL, common query parameter for each of the entities is id... Each endpoint should have at least two parameters to create search criteria.
If there isn't any defined query parameter then throw Custom Exception(created by you) that will stop REST endpoint to reach service layer. Exception should print appropriate message. 
If multiple query parameters are passed to the endpoint then query for searching should use AND condition in order to find appropriate records in DB.

You can use this link to see how controller is created and query for searching (https://www.javaguides.net/2022/04/search-rest-api-using-spring-boot.html)

Estimate Date: 09.03.2023

@AngelaM123 Issue is ready can start work on it.

**Comment by AngelaM123** [comment]
manage to make for every entity search endpoint ,used the suggested link above and tested examples

**Comment by MarinTrpenovski** [comment]
Closing this @AngelaM123 Code looks good;

**Comment by MarinTrpenovski** [comment]
Reopening this issue; Implementation is good but I  have one question, why use StringBuilder instead of String when create SQL query ? What is the difference between them ?

**Comment by AngelaM123** [comment]
We have a JVM that represents a heap memory for us when we use a String and when we create an object that we will want to modify later, a new object is created in the memory and the reference will point to the new object while the old object is floating and it will be deleted by the garbage collector, which during iteration performs is checking which objects are without references and since the old object does not show any reference it will be deleted, form the other side String Builder will modified the content without creating any new ,additional object in the memory and with that we can say that String Builder is much faster than String when concatenating or modifying a string
