### ISSUE TITLE
Investigate about Authentication and Authorization.

### ISSUE THREAD

**Issue by MarinTrpenovski** [MarinTrpenovski/Spring-Rest#74]
Idea of this issue is to get familiar with security in Web Applications with focus on REST services security.
Also need to understand what is Authorization and how it works in Web Applications.

Please read the following links as reference:
https://blog.openreplay.com/authentication-with-jwt-for-your-website/

Use this link as reference to understand what is jwt token , how its generated and how its decrypted.
https://jwt.io/

Basic Authentication and JWT Authentication
https://blog.risingstack.com/web-authentication-methods-explained/

Authentication vs Authorization
https://www.onelogin.com/learn/authentication-vs-authorization#:~:text=Authentication%20and%20authorization%20are%20two,authorization%20determines%20their%20access%20rights.

After reading about Authentication and Authorization answer following questions in the comment.

What is Authenticaiton and what is Authorization?
Which come first in Web application, Authentication or Authorization ?
What is JWT Authentication how it works explain the flow ?
What is Basic Authentication and how it works explain the flow ?
What is JWT token in Web application ?
Explain Role-Right approach in Authorization mechanism. Why we need to have Role and Rights separately ?
What need to be changed in Web application in order to apply Authentication ?
What need to be changed in Web application in order to apply Authorization ?

**Comment by AngelaM123** [comment]
I had made a research and came with some answers regarding  authentication ,authorization ,JWT authentication and token and as last the Role-Right approach in authorization mechanism. 
By definition authentication is the process of verifying a user or device before allowing access to a system or resources ,with other words authentication means confirming that a user is who they say they are. This ensures only those with authorized credentials gain access to secure systems, while authorization is the process of giving someone the ability to access a resource. In simple terms authentication is the process of verifying who a user is, while authorization is the process of verifying what they have access to.
In Web application authentication is the first step of a good identity and access management process because it works through passwords and other information provided or entered by the user while authorization works through settings that are implemented and maintained by the organization.
When it comes to JWT authentication firstly it is important to say that , JWTs are used as a secure way to authenticate users and share information. The token service encrypts the JWT using JSON Web Encryption and issues it to the client application. Client application receives the JWT in the response from the token service. Client application verifies the JSON Web token. Client application sends a request to authorization server's /token endpoint.
Basic authentication HTTP is a simple challenge and response mechanism with which a server can request authentication information from a client. This form of authentication can expose user names and passwords where the client passes the authentication information to the server in an Authorization header.
In Web application we also uste JWT token which is used to securely transfer information over the web. It can be used for an authentication system and can also be used for information exchange.
Providing permission to a user means allowing him to access a resource or execute a specific operation in a system. Permission-based access control is a technique that defines specific permissions for every entity using a system. A role-based system determines sets of permissions enforced to entities acting with similar objectives and privileges in a system. The principal benefit of using the role-based access control technique is easing the management of entities that access the system. It occurs because changes in permissions of a role are automatically applied to every entity with this role.
The flow for authentication 
When the credentials are received from the client's browser, the server validates these credentials and also generates a signed JWT containing all of the user information. The token is stateless, so it never gets stored on the server. Over the following requests, the token is passed to the server and then gets decoded in order to verify it on the server.
The flow for authorization
A user requests access to an application. The application determines that the user is not authenticated yet and redirects the user to the identity server. The user authenticates with the identity server. The identity server sends on successful authentication an access token/ID token to the user

**Comment by MarinTrpenovski** [comment]
Explanation is good @AngelaM123 for Authentication. But you mention in Authorization flow that users is check does he is authenticated or not... which is fine but that is part of Authentication process. 
![image](https://github.com/WORK-MENTOR/Spring-Rest/assets/27773018/5151d5dd-11a1-4a9d-aae3-62d35d26b49b)

What is the difference between Authentication and Authorization then ? 
How we apply Authorization in Web application ? Explanation about role-permisssion approach is good so you can use that direction to explain the flow.

**Comment by AngelaM123** [comment]
In the most simple way said , authentication is the process of verifying who someone is, whereas authorization is the process of verifying what specific applications, files, and data a user has access to. Authorization as mentioned before is a process by which a server determines if the client has permission to use a resource or access a file, it is usually coupled with authentication so that the server has some concept of who the client is that is requesting access , it is a mechanisms that can be generic because they do not need to know anything about what happens inside the application. They just allow or disallow access to the application

**Comment by MarinTrpenovski** [comment]
@AngelaM123 Explanation is good for Authorization , but explain the flow about authorization process. Step by step how we implemented in code and what happened during REST service execution. I think we already explain that.

**Comment by AngelaM123** [comment]
First thing a user do is login where it puts username and password , with that sends request to the service and get respond with that it has been made authentication . After this I receive in headers JWT token , here from the HTTP the filter takes the JWT header , checks if it has authorization than checks if the JWT token is valid from the  authorization header of the request, if it is not valid than it will throw exception , if it is valid it will be decrypted and added . The next step is the SQL query ,in my data base I have 5 tables user ,role , permission , user_role and role_permission with join I load permissions for that particular user. I get the permissions as List<String> and will set them in GrantedAuthority class to be added in the Spring Security Context, as last will need to be used the special annotation form spring security @PreAuthorize in the controller class , this will automatically check if the permission exists in GrantedAuthority class , if it is existent then it has access , if not it will get access denied 403.

**Comment by MarinTrpenovski** [comment]
@AngelaM123 Explanation looks good now. Closing this issue.
