### ISSUE TITLE
Modify database in order to support Authorization

### ISSUE THREAD

**Issue by MarinTrpenovski** [MarinTrpenovski/Spring-Rest#82]
Based on the investigation for issue #74 about Authorization now need to apply changes in the application.
First of all, need to modify the Database schema in order to support role-right (permissions) authorization approach.

Follow this link as reference in order to modify Database by adding appropriate tables and linked them https://www.nikhilajain.com/post/user-role-permission-model.

Use this link as reference https://www.baeldung.com/cs/role-vs-permission-based-access-control in order to answer questions below.
When you are done with the issue need to explain what is permissions-based access control and what is role-based access control? What is the difference ? When should use role-based and when permission-based access control ?

**Comment by AngelaM123** [comment]
I have applied the changes in the database in order to support authorization. Modified the Database schema in order to support role-right (permissions) authorization approach if needed will upload a picture . Used the references that were suggested in the above comment and also here are some answers for the question contained in this task
1.
Permissions-based access control is a security mechanism used to regulate and control access to digital resources, systems, or data within an organization or software application. In permissions-based access control, access is granted or denied based on predefined permissions or rules that are set up by administrators or system owners. These permissions dictate what actions users or groups of users can perform on a resource. These actions might include reading, writing, modifying, deleting, or executing
2.
Role-Based Access Control (RBAC) is a method of managing and controlling access to resources within a system based on roles. In RBAC, access decisions are made based on the roles that users have, rather than directly assigning individual permissions to users. This approach simplifies access management and enhances security in large and complex systems.
3.
Permissions-based access control and role-based access control (RBAC) are both methods used to manage and regulate access to resources within a system, but they operate slightly differently. Permissions-based access control focuses on directly assigning specific permissions to individual users or groups, allowing for precise control but potentially leading to administrative complexity. On the other hand, role-based access control relies on assigning roles to users, making access management more structured and easier to administer, especially in larger systems.
4.
The decision of whether to use role-based access control (RBAC) or permissions-based access control depends on the specific requirements and characteristics of your application, organization, and security needs. For example : If you have a large number of users who share similar responsibilities or access requirements, using RBAC can simplify administration. Instead of managing permissions for each user, you assign roles to groups of users with similar job functions , where permission-based access control is particularly useful in situations where you need fine-grained control over access to resources and where the access requirements vary significantly among users or groups

**Comment by MarinTrpenovski** [comment]
The description looks good. Need to check the database schema that you have created on your machine so that I can close this issue.
