### ISSUE TITLE
Create REST endpoint for JWT token validation

### ISSUE THREAD

**Issue by MarinTrpenovski** [MarinTrpenovski/Spring-Rest#92]
We need to create a new REST endpoint that will validate does JWT token in the header is valid or not, or is expired. 

If the token is valid return the token (string) otherwise if it's not valid throw an Exception that the token is expired.

These links can be used as references:

https://www.baeldung.com/java-jwt-check-expiry-no-exception
https://www.javainuse.com/spring/boot-jwt

**Comment by AngelaM123** [comment]
Created a new rest endpoint that validates does  JWT token in the header is valid or not, or is expired. If the token is valid will return the token as string if not will throw an Exception for expired token

**Comment by MarinTrpenovski** [comment]
@AngelaM123 Code looks good. Some notes before we close this issue.

1. What will happened if jwtToken doesn't exist in header ? How you handle this scenario  ?

![Image](https://github.com/WORK-MENTOR/Spring-Rest/assets/27773018/7bcf8a9e-3853-4e18-9de6-7daeee34be12)

2. You decode the token and check expiration date which is good. But how you handle scenario if token is not valid at all ?


![Image](https://github.com/WORK-MENTOR/Spring-Rest/assets/27773018/35b8f64f-61ac-4bc7-8ab7-16fb7b0a2008)

3. With current implementation try/catch I think that even if exception occur it will be handled and program will not terminate. So even if token can not be decrypted for some reason application will continue with execution, REST service will be completed I think. What is your opinion @AngelaM123  ?


![Image](https://github.com/WORK-MENTOR/Spring-Rest/assets/27773018/a24599e0-9c92-47f9-b109-7b00327b45e6)

Use this link https://www.scaler.com/topics/java/exception-handling-in-java/ to refresh your memory about Exceptions in java, what happened when we handle them in the application, and what happened when we throw them? 

4.  Declaration of boolean flag shouldn't be in same vertical line as method definition. Please move it right for better styling.
 

![Image](https://github.com/WORK-MENTOR/Spring-Rest/assets/27773018/10f32153-a021-4201-8033-2544e36253af)

You can fix this notes so we  can close this issue.

**Comment by AngelaM123** [comment]
Applied the required notes and here are some answers for the questions that are contained in this task
1.
When a JWT token is used, it's typically included in the header of an HTTP request to provide proof of the user's identity and their authorized actions. If a JWT token is missing from the header of an HTTP request, several scenarios might occur:
-Unauthorized Access: Without a valid JWT token, the server might treat the request as unauthorized. This means the user won't be granted access to the protected resources or actions they're trying to access.
-Authentication Failure: The server might respond with an authentication error, indicating that the user needs to provide valid authentication credentials (i.e., a valid JWT token) in order to proceed.
-API Endpoint Behavior: If the missing JWT token is related to an API endpoint, the API might return an error response with an appropriate HTTP status code (e.g., 401 Unauthorized or 403 Forbidden) along with a message indicating the reason for the error
-In summary, the exact behavior when a JWT token is missing from the header depends on how the application is designed and implemented. However, in most cases, missing JWT tokens will result in the user being unable to access protected resources until they provide a valid token
2.
 Scenarios where a token is not valid at all can be handle in more than one way few of them are 
-Token Validation:
Implement a robust token validation process. This involves checking the token's signature, expiration time, and other claims. If any of these checks fail, the token is considered invalid.
-Error Response:
When a token is found to be invalid, respond with an appropriate error message and HTTP status code. Common status codes include:401 Unauthorized: Indicates that the client's authentication credentials are missing or invalid.403 Forbidden: Indicates that the client's authentication credentials are valid, but they don't have permission to access the requested resource.
-Clear Error Messages:
Provide clear and informative error messages. This can help users understand why their authentication attempt failed and guide them toward the necessary steps to resolve the issue (e.g., logging in again, refreshing the token, etc.).
3.
When exceptions are handled effectively, the application can gracefully recover from errors and continue functioning
-Exception Handling: When an exception is raised, the application's code can include exception-handling mechanisms to deal with the error. This is usually done using try-catch (or try-except) blocks in many programming languages. The catch block contains the code to handle the specific exception that was raised. It allows developers to maintain control over the application's behavior in the face of errors, leading to better user experiences and more stable software.
-When you "throw" an exception in a programming language, you are signaling that an exceptional or error condition has occurred within your code. This action initiates a process where the runtime environment searches for a suitable "catch" block that can handle the thrown exception. Throwing exceptions is a mechanism that allows you to indicate errors and exceptional conditions in your code. By using appropriate catch blocks, you can manage error scenarios, handle them gracefully, and ensure that your application provides informative feedback to users while maintaining stability.

**Comment by MarinTrpenovski** [comment]
@AngelaM123 Code looks good please fix following note:

![image](https://github.com/WORK-MENTOR/Spring-Rest/assets/27773018/e5798a46-bd27-4bed-b326-cfdc5b443345)
isExpired initialization is redundant 

I think in one function its not good practice to return two different boolean flag, no matter that method will return boolean value.
Also logic in user controller need to be modified I think
![image](https://github.com/WORK-MENTOR/Spring-Rest/assets/27773018/6c431d24-0bff-48f4-95cd-1c48924e1746)

IN which case JWTException will be thrown ? I think isJWTnotValidOrExpired method as I notice in implementation if token is not valid will return notVerified boolean flag which is set to be true and never changed in the method.
So in user controller if check (isJWTnotValidOrExpired != true) will not pass this condition check and will throw Exception. 

PLease apply following notes. If need we can explain this again about JWT Authentication

**Comment by AngelaM123** [comment]
Applied the required notes form the above comment including the styling of the code and modified the logic in user controller

**Comment by MarinTrpenovski** [comment]
@AngelaM123 Code looks good now. Logic I think is correct. Did you test the endpoint via postman ?

One note in User Controller 
![image](https://github.com/WORK-MENTOR/Spring-Rest/assets/27773018/714dd477-d37b-4bba-a081-9729933b9b8c)

Did you need == true operation in if condition ? I think method isJWTnotValidOrExpired  return boolean so doesn't make sense to compare with boolean. Please fix this issue so we can close this issue. 

Test endpoint via postman. Its important to work and try to test several different scenarios.

**Comment by AngelaM123** [comment]
Applied the required note , and removed the == operation in the if condition ,tested via Postman as well

**Comment by MarinTrpenovski** [comment]
@AngelaM123 Code looks good. Fix following following note so we can close this issue.

Remove commented code
![image](https://github.com/WORK-MENTOR/Spring-Rest/assets/27773018/44909670-4774-4ec5-83b5-ef395d900386)

**Comment by AngelaM123** [comment]
Removed the commented code as required

**Comment by MarinTrpenovski** [comment]
@AngelaM123 That code is removed; but other code is commented now  remove it !!! 


![Image](https://github.com/WORK-MENTOR/Spring-Rest/assets/27773018/55952b62-a941-46dd-959d-e202a4479f0b)

**Comment by AngelaM123** [comment]
Removed the commented line from the code

**Comment by MarinTrpenovski** [comment]
@AngelaM123 Code looks good. I think you have typo issue in message. Fix typo issue so we can close this issue.


![Image](https://github.com/WORK-MENTOR/Spring-Rest/assets/27773018/68251af2-da17-4162-acd1-6995583cc8d2)

**Comment by AngelaM123** [comment]
Fixed the issue with the spelling

**Comment by MarinTrpenovski** [comment]
@AngelaM123 Code looks good now. Closing this issue.
